version: "3"

services:
  nginx:
    networks:
      flat-network:
        aliases :
          - localhost
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    container_name: dev-nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx/local-dev/:/etc/nginx/conf.d
    depends_on:
      - wp
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d > /etc/nginx/conf.d && nginx -g 'daemon off;'" 

  wp:
    image: wordpress:latest
    container_name: dev-wp
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_CONFIG_EXTRA:

        define('FS_METHOD', 'direct');

        define( 'WP_DEBUG', true );

        define( 'WP_DEBUG_LOG', '/tmp/logs' );

        define( 'WP_REDIS_HOST', 'redis' );

    env_file: .env
    volumes:
      - ./wordpress/wp-content:/var/www/html/wp-content
      - ./wordpress/logs:/tmp/logs
      - ./wordpress/wp-content/uploads/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - flat-network

  db:
    container_name: dev-db
    image: mysql:5.7.23
    env_file: .env
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - flat-network

  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   restart: always
  #   networks:
  #     - flat-network

networks:
  flat-network:
